#include "main.h"

static const char* levels_rome[6] = {"I", "II", "III", "IV", "V", "VI"};
static const char* levels_naming[6] = {"1st", "2nd", "3rd", "4th", "5th", "6th"};

BSDATA(feati) = {{"Alertness"},
{"ArmorProfeciencyLight"},
{"ArmorProfeciencyMedium", {}, {ArmorProfeciencyLight}},
{"ArmorProfeciencyHeavy", {}, {ArmorProfeciencyLight, ArmorProfeciencyMedium}},
{"BlindFight"},
{"Cleave", {13}, {PowerAttack}},
{"CombatCasting"},
{"CombatExpertise", {0, 0, 0, 13}},
{"CombatReflexes"},
{"DeadlyPrecision", {0, 15}, {}, 5},
{"DeflectsArrows", {0, 13}, {ImprovedUnarmedStrike}},
{"Dodge", {0, 13}},
{"Endurance", {}, {}},
{"FarShoot", {}, {PointBlankShoot}},
{"GreateFortitude"},
{"ImprovedCritical", {}, {}, 8},
{"ImprovedDisarm", {0, 0, 0, 13}, {CombatExpertise}},
{"ImprovedFeint", {0, 0, 0, 13}, {CombatExpertise}},
{"ImprovedInitiative"},
{"ImprovedOverrun", {13}, {PowerAttack}},
{"ImprovedSunder", {13}, {PowerAttack}},
{"ImprovedTrip", {0, 0, 0, 13}, {CombatExpertise}},
{"ImprovedUnarmedStrike"},
{"IronWill", {}, {}},
{"Leadership", {}, {}, 0, 6},
{"LightingReflexes"},
{"Mobiliy", {0, 13}, {Dodge}},
{"Multiattack"},
{"PointBlankShoot"},
{"PowerAttack", {13}},
{"PreciseShoot", {}, {PointBlankShoot}},
{"RapidShoot", {13}, {PointBlankShoot}},
{"RapidReload"},
{"ShieldProfeciency"},
{"ShortOnTheRun", {0, 13}, {Dodge, Mobiliy, PointBlankShoot}, 4},
{"SpellFocus"},
{"SpringAttack", {0, 13}, {Dodge, Mobiliy}, 4},
{"StunningFist", {0, 13, 0, 0, 13}, {ImprovedUnarmedStrike}, 8},
{"Toughness"},
{"Track"},
{"TwoWeaponFighting", {15}},
{"FocusAxes", {0}, {ProficiencyAxe}, 1},
{"FocusDaggers", {0}, {ProficiencyDagger}, 1},
{"FocusMaces", {0}, {ProficiencyMace}, 1},
{"FocusPolearm", {0}, {ProficiencySimple}, 1},
{"FocusShoting", {0}, {ProficiencySimple}, 1},
{"FocusSwords", {0}, {ProficiencyShortsword}, 1},
{"WhirlwindAttack", {0, 13, 0, 13}, {CombatExpertise, Dodge, Mobiliy, SpringAttack}, 4},
//
{"AxeProficiency"},
{"ClubProficiency"},
{"CrossbowProficiency"},
{"DaggerProficiency"},
{"GreatweaponProficiency", {}, {ProficiencyLongsword}},
{"HeavyCrossbowProficiency"},
{"MaceProficiency"},
{"SimpleWeaponProficiency"},
{"SpearProficiency"},
{"LongbowProficiency"},
{"LongswordProficiency"},
{"ShortbowProficiency"},
{"ScimitarProficiency"},
{"ShortswordProficiency"},
{"BastardswordProficiency", {}, {ProficiencyLongsword}},
{"CatanaProficiency"},
{"WaraxeProficiency", {}, {ProficiencyAxe}},
//
{"FastMovement"},
{"Illiteracy"},
//
{"HateOrcAndGoblins"},
{"Infravision"},
{"ImmunityToSleepSpell"},
{"FindSecrets"},
{"Lucky"},
{"PreciseThrower"},
{"SaveBonusVsEchantment"},
{"SaveBonusVsFear"},
{"SaveBonusVsIllusion"},
{"SaveBonusVsPoison"},
{"SaveBonusVsSpells"},
{"Stability"},
{"Stonecunning"},
};
assert_enum(feati, LastFeat)