#include "main.h"

skill_info skill_data[] = {{"No skill", "Нет навыка"},
{"Appraise", "Оценка", Intellegence, {CraftArmor, CraftWeapon, CraftDevice}},
{"Balance", "Балансирование", Dexterity},
{"Bluff", "Обман", Charisma},
{"Climb", "Лазить", Strenght, {Climb}},
{"Concentration", "Концентрация", Constitution},
{"Craft (Alchemy)", "Ремесло (Алхимия)", Intellegence},
{"Craft (Armor)", "Ремесло (Доспехи)", Intellegence},
{"Craft (Bow)", "Ремесло (Луки)", Intellegence},
{"Craft (Device)", "Ремесло (Устройства)", Intellegence},
{"Craft (Weapon)", "Ремесло (Оружие)", Intellegence},
{"Decipher script", "Расшифровать напись", Intellegence},
{"Diplomacy", "Дипломатия", Charisma, {Bluff, KnowledgeNobility, SenseMotive}},
{"Disable Device", "Обезвредить устройство", Intellegence},
{"Disguise", "Имитация", Charisma, {Bluff}},
{"Escape artist", "Мастер побегов", Dexterity, {UseRope}},
{"Forgery", "Подделка", Intellegence},
{"Gather information", "Добывание информации", Charisma},
{"Handle animal", "Приручение животных", Charisma},
{"Heal", "Лечение", Wisdow},
{"Hide", "Прятаться", Dexterity},
{"Intimidate", "Запугивание", Charisma, {Bluff}},
{"Jump", "Прыжки", Strenght},
{"Knowledge (Arcana)", "Знания мистики", Intellegence},
{"Knowledge (History)", "Знания истории", Intellegence},
{"Knowledge (Nature)", "Знания природы", Intellegence},
{"Knowledge (Nobility)", "Знания геральдики", Intellegence},
{"Knowledge (Religion)", "Знания религии", Intellegence},
{"Listen", "Слушать", Wisdow},
{"Move silently", "Двигаться тихо", Dexterity},
{"Open lock", "Открывать замки", Dexterity},
{"Perform", "Артистизм", Charisma},
{"Ride", "Езда верхом", Dexterity, {HandleAnimal}},
{"Search", "Поиск", Intellegence},
{"Sense motive", "Чувство мотивов", Wisdow},
{"Sleight of hand", "Ловкость рук", Dexterity, {Bluff}},
{"Speak language", "Разговаривать на языке", Intellegence},
{"Spellcraft", "Знания заклинаний", Intellegence, {KnowledgeArcana}},
{"Spot", "Наблюдательность", Wisdow},
{"Survival", "Выживание", Wisdow, {KnowledgeNature}},
{"Swim", "Плавание", Strenght},
{"Tumble", "Акробатика", Dexterity, {Jump}},
{"Use magic device", "Использовать волшебные устройства", Charisma, {DecipherScript, Spellcraft}},
{"Use rope", "Использовать веревку", Dexterity, {EscapeArtist}},
};
assert_enum(skill, LastSkill);
getstr_enum(skill);