#include "main.h"

BSDATA(skilli) = {{"NoSkill"},
{"Appraise", Intellegence, {CraftArmor, CraftWeapon, CraftDevice}},
{"Balance", Dexterity},
{"Bluff", Charisma},
{"Climb", Strenght, {Climb}},
{"Concentration", Constitution},
{"CraftAlchemy", Intellegence},
{"CraftArmor", Intellegence},
{"CraftBow", Intellegence},
{"CraftDevice", Intellegence},
{"CraftWeapon", Intellegence},
{"DecipherScript", Intellegence},
{"Diplomacy", Charisma, {Bluff, KnowledgeNobility, SenseMotive}},
{"DisableDevice", Intellegence},
{"Disguise", Charisma, {Bluff}},
{"EscapeArtist", Dexterity, {UseRope}},
{"Forgery", Intellegence},
{"GatherInformation", Charisma},
{"HandleAnimal", Charisma},
{"Heal", Wisdow},
{"Hide", Dexterity},
{"Intimidate", Charisma, {Bluff}},
{"Jump", Strenght},
{"KnowledgeArcana", Intellegence},
{"KnowledgeHistory", Intellegence},
{"KnowledgeNature", Intellegence},
{"KnowledgeNobility", Intellegence},
{"KnowledgeReligion", Intellegence},
{"Listen", Wisdow},
{"MoveSilently", Dexterity},
{"OpenLock", Dexterity},
{"Perform", Charisma},
{"Ride", Dexterity, {HandleAnimal}},
{"Search", Intellegence},
{"SenseMotive", Wisdow},
{"SleightOfHand", Dexterity, {Bluff}},
{"SpeakLanguage", Intellegence},
{"Spellcraft", Intellegence, {KnowledgeArcana}},
{"Spot", Wisdow},
{"Survival", Wisdow, {KnowledgeNature}},
{"Swim", Strenght},
{"Tumble", Dexterity, {Jump}},
{"UseMagicDevice", Charisma, {DecipherScript, Spellcraft}},
{"UseRope", Dexterity, {EscapeArtist}},
};
assert_enum(skilli, LastSkill)