#include "main.h"

BSDATA(spelli) = {{"No spell", "Нет Заклинания", "SPWI104C"},
//
{"Armor of Faith", "Доспех веры", "SPPR115C", Abjuration, {{Cleric, 1}}},
{"Bane", "Погибель", "SPPR111C", Enchantment, {{Cleric, 1}}},
{"Bless", "Благословение", "SPPR101C", Conjuration, {{Cleric, 1}}},
{"Command", "Команда", "SPPR102C", Enchantment, {{Cleric, 1}}},
{"Cure Light Wounds", "Исцелить легкое ранение", "SPPR103C", Conjuration, {{Cleric, 1}}},
{"Doom", "Злой рок", "SPPR114C", Enchantment, {{Cleric, 1}}},
{"Entangle", "Опутать", "SPPR105C", Transmutation, {{Cleric, 1}}},
{"Faerie Fire", "Волшебный огонь", "SPPR116C", Evocation, {{Cleric, 1}}},
{"Flame Strike", "Огненный удар", "SPPR503C", Evocation, {{Cleric, 5}}},
{"Frost Fingers", "Морозные пальцы", "SPPR117C", Transmutation, {{Cleric, 1}}},
{"Glyph of Warding", "Глиф защиты", "SPPR304C", Abjuration, {{Cleric, 3}}},
{"Hold Person", "Остановить персону", "SPPR208C", Enchantment, {{Cleric, 2}}},
{"Inflict Light Wounds", "Нанести легкое ранение", "SPPR112C", Necromancy, {{Cleric, 1}}},
{"Magic Stone", "Волшебный камень", "SPPR106C", Transmutation, {{Cleric, 1}}},
{"Protection From Evil", "Защита от зла", "SPPR107C", Abjuration, {{Cleric, 1}}},
{"Remove Fear", "Убрать страх", "SPPR108C", Abjuration, {{Cleric, 1}}},
{"Remove Paralysis", "Убрать паралич", "SPPR308C", Abjuration, {{Cleric, 3}}},
{"Sanctuary", "Убежище", "SPPR109C", Abjuration, {{Cleric, 1}}},
{"Shillelagh", "Дубинка", "SPPR110C", Transmutation, {{Druid, 1}}},
{"Sunscorch", "Солнечный ожег", "SPPR113C", Evocation, {{Cleric, 1}}},
{"Antichickenator", "Антикурица", "SPPR302C", NoSchool, {{Sorcerer, 1}, {Wizard, 1}}},
{"Burning Hands", "Огненные руки", "SPWI103C", Transmutation, {{Sorcerer, 1}, {Wizard, 1}}},
{"Charm Person", "Очаровать персону", "SPWI104C", Enchantment, {{Sorcerer, 1}, {Wizard, 1}}},
{"Chill Touch", "Ледяное касание", "SPWI117C", Necromancy, {{Sorcerer, 1}, {Wizard, 1}}},
{"Chromatic Orb", "Радужная сфера", "SPWI118C", Evocation, {{Sorcerer, 1}, {Wizard, 1}}},
{"Color Spray", "Цветные брызги", "SPWI105C", Transmutation, {{Sorcerer, 1}, {Wizard, 1}}},
{"Dispel Magic", "Рассеять магию", "SPwi302C", Abjuration, {{Sorcerer, 3}, {Wizard, 3}}},
{"Eagle's Splendor", "Орлиное великолепие", "SPWI107C", Enchantment, {{Sorcerer, 1}, {Wizard, 1}}},
{"Generic Abjuration", "Базовый оберег", "SPWI112C", Evocation, {{Sorcerer, 1}, {Wizard, 1}}},
{"Grease", "Смазка", "SPWI101C", Conjuration, {{Sorcerer, 1}, {Wizard, 1}}},
{"Ice Dagger", "Ледяной кинжал", "SPWI122C", Evocation, {{Sorcerer, 1}, {Wizard, 1}}},
{"Identify", "Опознание", "SPWI110C", Divination, {{Sorcerer, 1}, {Wizard, 1}}},
{"Larloch's Minor Drain", "Слабое иссушение Ларлоха", "SPWI119C", Necromancy, {{Sorcerer, 1}, {Wizard, 1}}},
{"Mage Armor", "Доспех мага", "SPWI102C", Conjuration, {{Sorcerer, 1}, {Wizard, 1}}},
{"Magic Missile", "Волшебный снаряд", "SPWI112C", Evocation, {{Sorcerer, 1}, {Wizard, 1}}},
{"Minor Mirror Image", "Слабое зеркальное отображение", "SPWI120C", Illusion, {{Sorcerer, 1}, {Wizard, 1}}},
{"Protection from Petrification", "Защита от окаменения", "SPWI108C", Abjuration, {{Sorcerer, 1}, {Wizard, 1}}},
{"Shield", "Щит", "SPWI114C", Abjuration, {{Sorcerer, 1}, {Wizard, 1}}},
{"Shocking Grasp", "Шокирующая хватка", "SPWI115C", Transmutation, {{Sorcerer, 1}, {Wizard, 1}}},
{"Sleep", "Сон", "SPWI116C", Enchantment, {{Sorcerer, 1}, {Wizard, 1}}},
{"Spook", "Бабай", "SPWI121C", Illusion, {{Sorcerer, 1}, {Wizard, 1}}},
{"Summon Monster I", "Призыв монстра I", "SPWI124C", Conjuration, {{Sorcerer, 1}, {Wizard, 1}}}, };
assert_enum(spelli, LastSpell)

bool creature::is(spell_s id, class_s cls, int level) {
	return bsdata<spelli>::elements[id].levels[cls] >= level;
}