#include "main.h"

BSDATA(spelli) = {{"NoSpell", "Нет Заклинания", "SPWI104C"},
//
{"ArmorOfFaith", "Доспех веры", "SPPR115C", Abjuration, {{Cleric, 1}}},
{"Bane", "Погибель", "SPPR111C", Enchantment, {{Cleric, 1}}},
{"Bless", "Благословение", "SPPR101C", Conjuration, {{Cleric, 1}}},
{"Command", "Команда", "SPPR102C", Enchantment, {{Cleric, 1}}},
{"CureLightWounds", "Исцелить легкое ранение", "SPPR103C", Conjuration, {{Cleric, 1}}},
{"Doom", "Злой рок", "SPPR114C", Enchantment, {{Cleric, 1}}},
{"Entangle", "Опутать", "SPPR105C", Transmutation, {{Cleric, 1}}},
{"FaerieFire", "Волшебный огонь", "SPPR116C", Evocation, {{Cleric, 1}}},
{"FlameStrike", "Огненный удар", "SPPR503C", Evocation, {{Cleric, 5}}},
{"FrostFingers", "Морозные пальцы", "SPPR117C", Transmutation, {{Cleric, 1}}},
{"GlyphOfWarding", "Глиф защиты", "SPPR304C", Abjuration, {{Cleric, 3}}},
{"HoldPerson", "Остановить персону", "SPPR208C", Enchantment, {{Cleric, 2}}},
{"InflictLightWounds", "Нанести легкое ранение", "SPPR112C", Necromancy, {{Cleric, 1}}},
{"MagicStone", "Волшебный камень", "SPPR106C", Transmutation, {{Cleric, 1}}},
{"ProtectionFromEvil", "Защита от зла", "SPPR107C", Abjuration, {{Cleric, 1}}},
{"RemoveFear", "Убрать страх", "SPPR108C", Abjuration, {{Cleric, 1}}},
{"RemoveParalysis", "Убрать паралич", "SPPR308C", Abjuration, {{Cleric, 3}}},
{"Sanctuary", "Убежище", "SPPR109C", Abjuration, {{Cleric, 1}}},
{"Shillelagh", "Дубинка", "SPPR110C", Transmutation, {{Druid, 1}}},
{"Sunscorch", "Солнечный ожег", "SPPR113C", Evocation, {{Cleric, 1}}},
{"Antichickenator", "Антикурица", "SPPR302C", NoSchool, {{Sorcerer, 1}, {Wizard, 1}}},
{"BurningHands", "Огненные руки", "SPWI103C", Transmutation, {{Sorcerer, 1}, {Wizard, 1}}},
{"CharmPerson", "Очаровать персону", "SPWI104C", Enchantment, {{Sorcerer, 1}, {Wizard, 1}}},
{"ChillTouch", "Ледяное касание", "SPWI117C", Necromancy, {{Sorcerer, 1}, {Wizard, 1}}},
{"ChromaticOrb", "Радужная сфера", "SPWI118C", Evocation, {{Sorcerer, 1}, {Wizard, 1}}},
{"ColorSpray", "Цветные брызги", "SPWI105C", Transmutation, {{Sorcerer, 1}, {Wizard, 1}}},
{"DispelMagic", "Рассеять магию", "SPwi302C", Abjuration, {{Sorcerer, 3}, {Wizard, 3}}},
{"EaglesSplendor", "Орлиное великолепие", "SPWI107C", Enchantment, {{Sorcerer, 1}, {Wizard, 1}}},
{"GenericAbjuration", "Базовый оберег", "SPWI112C", Evocation, {{Sorcerer, 1}, {Wizard, 1}}},
{"Grease", "Смазка", "SPWI101C", Conjuration, {{Sorcerer, 1}, {Wizard, 1}}},
{"IceDagger", "Ледяной кинжал", "SPWI122C", Evocation, {{Sorcerer, 1}, {Wizard, 1}}},
{"Identify", "Опознание", "SPWI110C", Divination, {{Sorcerer, 1}, {Wizard, 1}}},
{"LarlochsMinorDrain", "Слабое иссушение Ларлоха", "SPWI119C", Necromancy, {{Sorcerer, 1}, {Wizard, 1}}},
{"MageArmor", "Доспех мага", "SPWI102C", Conjuration, {{Sorcerer, 1}, {Wizard, 1}}},
{"MagicMissile", "Волшебный снаряд", "SPWI112C", Evocation, {{Sorcerer, 1}, {Wizard, 1}}},
{"MinorMirrorImage", "Слабое зеркальное отображение", "SPWI120C", Illusion, {{Sorcerer, 1}, {Wizard, 1}}},
{"ProtectionFromPetrification", "Защита от окаменения", "SPWI108C", Abjuration, {{Sorcerer, 1}, {Wizard, 1}}},
{"Shield", "Щит", "SPWI114C", Abjuration, {{Sorcerer, 1}, {Wizard, 1}}},
{"ShockingGrasp", "Шокирующая хватка", "SPWI115C", Transmutation, {{Sorcerer, 1}, {Wizard, 1}}},
{"Sleep", "Сон", "SPWI116C", Enchantment, {{Sorcerer, 1}, {Wizard, 1}}},
{"Spook", "Бабай", "SPWI121C", Illusion, {{Sorcerer, 1}, {Wizard, 1}}},
{"SummonMonsterI", "Призыв монстра I", "SPWI124C", Conjuration, {{Sorcerer, 1}, {Wizard, 1}}}, };
assert_enum(spelli, LastSpell)

bool creature::is(spell_s id, class_s cls, int level) {
	return bsdata<spelli>::elements[id].levels[cls] >= level;
}