#include "main.h"

static struct token {
	const char*	name[2];
	int			parent;
	const char*	identifier;
} objects[] = {{"None"},
// Attributes
{{"Strenght"}},
{{"Dexterity"}},
{{"Constitution"}},
{{"Intellegence"}},
{{"Wisdow"}},
{{"Charisma"}},
// Classes
{{"Barbarian"}},
{{"Bard"}},
{{"Cleric"}},
{{"Druid"}},
{{"Fighter"}},
{{"Monk"}},
{{"Paladin"}},
{{"Ranger"}},
{{"Rogue"}},
{{"Sorcerer"}},
{{"Wizard"}},
//
{{"Adept"}},
{{"Aristocrat"}},
{{"Beast"}},
{{"Commoner"}},
{{"Monster"}},
{{"Undead"}},
{{"Warrior"}},
// Skills
{{"Appraise", "Оценка"}},
{{"Balance", "Балансирование"}},
{{"Bluff", "Обман"}},
{{"Climb", "Лазить"}},
{{"Concentration", "Концентрация"}},
{{"Craft (Alchemy)", "Ремесло (Алхимия)"}},
{{"Craft (Armor)", "Ремесло (Доспехи)"}},
{{"Craft (Bow)", "Ремесло (Луки)"}},
{{"Craft (Device)", "Ремесло (Устройства)"}},
{{"Craft (Weapon)", "Ремесло (Оружие)"}},
{{"Decipher script"}},
{{"Diplomacy", "Дипломатия"}},
{{"Disable Device"}},
{{"Disguise", "Имитация"}},
{{"Escape artist", "Мастер побегов"}},
{{"Forgery", "Подделка"}},
{{"Gather information", "Добывание информации"}},
{{"Handle animal"}},
{{"Heal", "Лечение"}},
{{"Hide", "Прятаться"}},
{{"Intimidate"}},
{{"Jump"}},
{{"Knowledge (Arcana)"}},
{{"Knowledge (History)"}},
{{"Knowledge (Nature)"}},
{{"Knowledge (Nobility)"}},
{{"Knowledge (Religion)"}},
{{"Listen"}},
{{"Move silently"}},
{{"Open lock"}},
{{"Perform"}},
{{"Ride"}},
{{"Search"}},
{{"Sense motive"}},
{{"Sleight of hand"}},
{{"Speak language"}},
{{"Spellcraft"}},
{{"Spot"}},
{{"Survival"}},
{{"Swim"}},
{{"Tumble"}},
{{"Use magic device"}},
{{"Use rope"}},
// Feats
{{"Alertness"}},
{{"Blind-fight"}},
{{"Cleave"}},
{{"Combat casting"}},
{{"Combat expertise"}},
{{"Combat reflexes"}},
{{"Deadly precision"}},
{{"Deflect arrows"}},
{{"Dodge"}},
{{"Endurance"}},
{{"Far shoot"}},
{{"Greate fortitude"}},
{{"Improved critical"}},
{{"Improved disarm"}},
{{"Improved feint"}},
{{"Improved initiative"}},
{{"Improved overrun"}},
{{"Improved sunder"}},
{{"Improved trip"}},
{{"Improved unarmed strike"}},
{{"Iron will"}},
{{"Leadership"}},
{{"Lighting reflexes"}},
{{"Mobility"}},
{{"Multiattack"}},
{{"Point-blank shoot"}},
{{"Power attack"}},
{{"Precise shoot"}},
{{"Rapid shoot"}},
{{"Rapid reload"}},
{{"Shoot on the run"}},
{{"Spell focus (Abjuration)"}},
{{"Spell focus (Conjuration)"}},
{{"Spell focus (Divination)"}},
{{"Spell focus (Enchantment)"}},
{{"Spell focus (Evocation)"}},
{{"Spell focus (Illusion)"}},
{{"Spell focus (Necromancy)"}},
{{"Spell focus (Transmutation)"}},
{{"Spring attack"}},
{{"Stunning fist"}},
{{"Toughness"}},
{{"Track"}},
{{"Two-weapon fighting"}},
{{"Whirlwind attack"}},
{{"Armor profeciency"}},
{{"Axe proficiency"}},
{{"Mace proficiency"}},
{{"Bow proficiency"}},
{{"Crossbow proficiency"}},
{{"Dagger proficiency"}},
{{"Polearm proficiency"}},
{{"Shield proficiency"}},
{{"Sword proficiency"}},
{{"Throwing weapon proficiency"}},
{{"Two-handed sword proficiency"}},
{{"Unarmed fighting"}},
//
{{"Active weapon"}},
{{"First name element"}},
{{"Second name element"}},
{{"Third name element"}},
{{"Portrait"}},
{{"Skin color"}},
{{"Hair color"}},
{{"Major color"}},
{{"Minor color"}},
//
{{"Race", "Раса"}},
{{"Aligment", "Мировозрение"}},
{{"Diety", "Божество"}},
{{"Gender", "Пол"}},
{{"Class", "Класс"}},
{{"Skills", "Навыки"}},
{{"Feats", "Особенности"}},
{{"Appearance", "Внешний вид"}},
// Gender
{{"Male", "Мужчина"}},
{{"Female", "Женщина"}},
// Race
{{"Dwarf"}},
{{"Elf"}},
{{"Gnome"}},
{{"Half-elf"}},
{{"Half-orc"}},
{{"Halfling"}},
{{"Human"}},
// Alignment
{{"Lawful Good", "Законопослушный добрый"}},
{{"Neutral Good", "Нейтральный добрый"}},
{{"Chaotic Good", "Хаотичный добрый"}},
{{"Lawful Neutral", "Законопослушный нейтральный"}},
{{"True Neutral", "Полностью нейтральный"}},
{{"Chaotic Neutral", "Хаотичный нейтральный"}},
{{"Lawful Evil", "Законопослушный злой"}},
{{"Neutral Evil", "Нейтральный злой"}},
{{"Chaotic Evil", "Хаотичный злой"}},
// Magic schools
{{"Abjuration"}},
{{"Conjuration"}},
{{"Divination"}},
{{"Enchantment"}},
{{"Evocation"}},
{{"Illusion"}},
{{"Necromancy"}},
{{"Transmutation"}},
// Gods
{{"Bane"}},
{{"Chauntea"}},
{{"Illmater"}},
{{"Gruumsh"}},
{{"Helm"}},
{{"Kelemvor"}},
{{"Kossuth"}},
{{"Lathander"}},
{{"Lolth"}},
{{"Mask"}},
{{"Mystra"}},
{{"Moradin"}},
{{"Oghma"}},
{{"Shar"}},
{{"Tempus"}},
{{"Tymora"}},
{{"Tyr"}},
{{"Umberly"}},
// Spell types
{{"Calling"}},
{{"Creation"}},
{{"Healing"}},
{{"Summoning"}},
{{"Charm"}},
{{"Compulsion"}},
{{"Figment"}},
{{"Glamour"}},
{{"Phantasmal"}},
{{"Shadowing"}},
//
{{"Base attack bonus"}},
{{"Character level"}},
{{"Spellcaster level"}},
// Commands
{{"Main Menu"}},
{{"Next"}},
{{"Back"}},
{{"Import"}},
{{"Biography"}},
{{"Finish"}},
{{"Start Over"}},
{{"Memorize spells"}},
{{"Reroll"}},
{{"Save Values"}},
{{"Load Values"}},
{{"Abilities"}},
};